export const COURSES = [
  {
    code: "MATH 301",
    title: "Advanced Calculus",
    professor: "Prof. Anderson",
    time: "Mon/Wed 10:00 AM",
    color: "blue",
    marksObtained: 85,
    totalMarks: 100,
  },
  {
    code: "PHYS 201",
    title: "Quantum Physics",
    professor: "Prof. Thompson",
    time: "Tue/Thu 2:00 PM",
    color: "purple",
    marksObtained: 85,
    totalMarks: 100,
  },
  {
    code: "CS 401",
    title: "Data Structures",
    professor: "Prof. Martinez",
    time: "Mon/Wed 2:00 PM",
    color: "green",
    marksObtained: 85,
    totalMarks: 100,
  },
  {
    code: "PSY 301",
    title: "Cognitive Psychology",
    professor: "Prof. Williams",
    time: "Tue/Thu 11:00 AM",
    color: "red",
    marksObtained: 85,
    totalMarks: 100,
  },
  {
    code: "HIST 202",
    title: "World History",
    professor: "Prof. Johnson",
    time: "Fri 9:00 AM",
    color: "yellow",
    marksObtained: 85,
    totalMarks: 100,
  },
  {
    code: "BIO 301",
    title: "Molecular Biology",
    professor: "Prof. Garcia",
    time: "Mon/Wed 8:00 AM",
    color: "pink",
    marksObtained: 85,
    totalMarks: 100,
  },
];
